version: '3.7'

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-ws-consumer
    command: sh -c "sleep 30 && go run main.go"
    depends_on:
      - wireshark
    volumes:
      - .:/opt/app

  wireshark:
    image: lscr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 3000:3000
    volumes:
      - ./.docker/wireshark:/config